import { auth } from "@clerk/nextjs";
import NavbarMain from "~/components/navbars/navbar-main";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { sessionClaims } = auth();

  return (
    <>
      {/* navbar */}
      <NavbarMain role={sessionClaims?.metadata.role} />
      <main className="p-6">{children}</main>
    </>
  );
}
