export const metadata = {
  title: "SIP - UNSRIT",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex h-[75vh] items-center justify-center p-4 md:h-[80vh]">
        <div>{children}</div>
      </div>
    </>
  );
}
